### ISSUE TITLE
Implement distributed word histogram

### ISSUE THREAD

**Issue by McSinyx** [Huy-Ngo/ds2021#9]
Use any MapReduce framework of your choice to implement word histogram.  Note that in Python there's collections.Counter.

**Comment by Huy-Ngo** [comment]
Distributed Windows Computer?

**Comment by McSinyx** [comment]
Yes.

**Comment by Huy-Ngo** [comment]
This one is not wc(1), because afaik wc only counts all the words rather than how many words each type has.

**Comment by McSinyx** [comment]
You're right, edited.
